GET http://localhost:5000/new

###

POST http://localhost:5000/new
Content-Type: application/json

{
  "name": "test",
  "elo": 1200
}

###

POST http://localhost:5000/new
Content-Type: application/json

{
  "name": "bahia",
  "elo": 1300
}
